# Generated by Django 2.0.3 on 2018-03-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('iata', models.CharField(max_length=2, null=True)),
                ('icao', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=10)),
                ('src_airport', models.CharField(max_length=4)),
                ('dst_airport', models.CharField(max_length=4)),
                ('num_of_stops', models.IntegerField(null=True)),
                ('src_time', models.TimeField()),
                ('dst_time', models.TimeField()),
            ],
        ),
    ]
