<<<<<<< HEAD
# Generated by Django 2.0.3 on 2018-03-24 20:10
=======
# Generated by Django 2.0.3 on 2018-03-25 23:33
>>>>>>> master

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=60)),
                ('iata', models.CharField(max_length=2, null=True)),
                ('icao', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=10)),
                ('src_airport', models.CharField(max_length=4)),
                ('dst_airport', models.CharField(max_length=4)),
                ('num_of_stops', models.IntegerField(null=True)),
                ('src_time', models.TimeField()),
                ('dst_time', models.TimeField()),
=======
                ('flight_no', models.CharField(max_length=10)),
                ('stop_no', models.IntegerField()),
                ('airline_id', models.CharField(blank=True, max_length=4)),
                ('src_airport', models.CharField(blank=True, max_length=4)),
                ('dst_airport', models.CharField(blank=True, max_length=4)),
                ('num_of_seats', models.IntegerField(null=True)),
                ('num_of_stops', models.IntegerField(null=True)),
                ('src_time', models.TimeField()),
                ('dst_time', models.TimeField()),
                ('arrive_day', models.IntegerField(null=True)),
                ('working_days', models.CharField(max_length=40)),
                ('fare', models.FloatField(null=True)),
                ('fare_restriction', models.CharField(max_length=40)),
>>>>>>> master
            ],
        ),
    ]
