# Generated by Django 2.0.3 on 2018-03-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='qqame',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
