# Generated by Django 2.0.3 on 2018-03-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20180326_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='flight_no',
            field=models.IntegerField(null=True),
        ),
    ]
