# Generated by Django 2.0.3 on 2018-03-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_airline_ssssame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airline',
            name='qqame',
        ),
        migrations.RemoveField(
            model_name='airline',
            name='ssssame',
        ),
    ]
