# Generated by Django 2.0.3 on 2018-03-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20180315_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('flight_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('source_airport', models.CharField(max_length=4)),
                ('destination_airport', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='airline',
            name='iata',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='airline',
            name='icao',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
