# Generated by Django 2.0.3 on 2018-03-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20180315_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='destination_airport',
            new_name='dst_airport',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='source_airport',
            new_name='src_airport',
        ),
        migrations.AddField(
            model_name='route',
            name='dst_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='src_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='flight_no',
            field=models.CharField(max_length=10),
        ),
    ]
