# Generated by Django 2.0.3 on 2018-03-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20180318_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='num_of_stops',
            field=models.IntegerField(null=True),
        ),
    ]
