# Generated by Django 2.0.3 on 2018-03-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_no', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('reservation_status', models.CharField(choices=[('A', 'Accepted'), ('C', 'Cancelled')], default='A', max_length=20)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('num_legs', models.IntegerField(null=True)),
                ('fare_restrictions', models.CharField(blank=True, max_length=100)),
                ('passengers', models.CharField(blank=True, max_length=100)),
                ('total_fare', models.FloatField(blank=True)),
                ('booking_fee', models.FloatField(blank=True)),
                ('customer_rep', models.CharField(blank=True, max_length=25)),
            ],
        ),
    ]
