# Generated by Django 2.0.3 on 2018-03-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_no', models.CharField(blank=True, max_length=100)),
                ('leg_no', models.IntegerField(null=True)),
                ('airline_id', models.CharField(blank=True, max_length=3)),
                ('flight_no', models.IntegerField()),
                ('stop_no', models.IntegerField(null=True)),
                ('seat_num', models.IntegerField(null=True)),
                ('src_time', models.DateTimeField(blank=True)),
                ('dst_time', models.DateTimeField(blank=True)),
                ('cabin', models.CharField(blank=True, choices=[('E', 'Economy'), ('PE', 'Premium Economy'), ('B', 'Business'), ('FC', 'First Class')], max_length=20)),
                ('meal_preference', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
